import = [
  # "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-frappe.toml",
  # "~/.config/alacritty/catppuccin-latte.toml"
]

[colors]
draw_bold_text_with_bright_colors = false

[colors.cursor]
cursor = "0x268bd2"
text = "0xeee8d5"

[keyboard]
bindings = [
  # tmux session | picker (sesh)
  { key = "K", mods = "Command|Shift", chars = "\u0000k" },
  # tmux | command
  { key = ";", mods = "Command", chars = "\u0000:" },
  # tmux | refresh
  { key = "R", mods = "Command", chars = "\u0000r" },
  # tmux split | vertically
  { key = "D", mods = "Command", chars = "\u0000v" },
  # tmux split | horizontally
  { key = "D", mods = "Command|Shift", chars = "\u0000s" },
  # tmux pane | new
  { key = "T", mods = "Command", chars = "\u0000c" },
  # tmux pane | last
  { key = "L", mods = "Command", chars = "\u0000l" },
  # tmux pane | last session
  { key = "L", mods = "Command|Shift", chars = "\u0000L" },
  # tmux window | prev
  { key = "Tab", mods = "Control|Shift", chars = "\u0000p" },
  { key = "[", mods = "Command|Shift", chars = "\u0000p" },
  # tmux window | next
  { key = "Tab", mods = "Control", chars = "\u0000n" },
  { key = "]", mods = "Command|Shift", chars = "\u0000n" },
  # tmux window | select by number
  { key = "1", mods = "Command", chars = "\u00001" },
  { key = "2", mods = "Command", chars = "\u00002" },
  { key = "3", mods = "Command", chars = "\u00003" },
  { key = "4", mods = "Command", chars = "\u00004" },
  { key = "5", mods = "Command", chars = "\u00005" },
  { key = "6", mods = "Command", chars = "\u00006" },
  { key = "7", mods = "Command", chars = "\u00007" },
  { key = "8", mods = "Command", chars = "\u00008" },
  { key = "9", mods = "Command", chars = "\u00009" },
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 5

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 10

[window]
decorations = "buttonless"
dynamic_title = true
dynamic_padding = false

[window.padding]
x = 0
y = 0
