# format=' $all'
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
${custom.tmux}\
$nodejs\
$line_break\
$character
"""

[custom.tmux]
command = "echo 'tmux'"
when = "[ $TMUX ]"  # Condition to check
style = "default"  # Style for the text
format = '[in](blue) [$symbol($output)]($style) '
# format = 'in [$symbol($output)]($style) '

[character]
format = ' $symbol '
success_symbol = ''
error_symbol = ''

[directory]
truncation_length = 0
truncate_to_repo = false
style = "default"

[git_branch]
symbol = ""
style = "default"
format = '[on](blue) [$branch(:$remote_branch)]($style) '
# format = 'on [$symbol$branch(:$remote_branch)]($style) '
# format = 'on [$symbol$branch(:$remote_branch)]($style) '
# symbol = " "

[git_status]
disabled = true
#ADDED=''
#UNMERGED=''
format = '([$all_status$ahead_behind]($style) )'
deleted = ''
diverged = ''
modified = ''
untracked = "?"
renamed = ''
stashed = ''

[lua]
disabled = true

[python]
disabled = true

[nodejs]
disabled = false
format = '[$symbol](blue)[($version)]($style)'
style = "default"
# format = 'via [$symbol($version )]($style)'

[package]
disabled = true

[golang]
disabled = true
