# format=' $all'
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$character
"""

[character]
format = ' $symbol '
success_symbol = ''
error_symbol = ''

[directory]
truncation_length = 0
truncate_to_repo = false
style = "blue"

[git_branch]
symbol = ""
style = "purple"
# symbol = " "

[git_status]
#disabled = true
#ADDED=''
#UNMERGED=''
format = '([$all_status$ahead_behind]($style) )'
deleted = ''
diverged = ''
modified = ''
untracked = "?"
renamed = ''
stashed = ''

[lua]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[golang]
disabled = true
