# format=' $all'
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
${custom.tmux}\
$line_break\
$character
"""

[custom.tmux]
command = "echo 'in tmux'"
when = "[ $TMUX ]"  # Condition to check
style = "cyan"  # Style for the text

[character]
format = ' $symbol '
success_symbol = ''
error_symbol = ''

[directory]
truncation_length = 0
truncate_to_repo = false
# style = "blue"

[git_branch]
symbol = ""
# style = "blue"
# symbol = " "

[git_status]
disabled = true
#ADDED=''
#UNMERGED=''
format = '([$all_status$ahead_behind]($style) )'
deleted = ''
diverged = ''
modified = ''
untracked = "?"
renamed = ''
stashed = ''

[lua]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[golang]
disabled = true
