[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x545862"
blue = "0x565c64"
cyan = "0xbe5046"
green = "0x353b45"
magenta = "0xb6bdca"
red = "0xd19a66"
white = "0xc8ccd4"
yellow = "0x3e4451"

[colors.cursor]
cursor = "0xabb2bf"
text = "0x282c34"

[colors.normal]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xe5c07b"

[colors.primary]
background = "0x282c34"
foreground = "0xabb2bf"
