# Base16 Grayscale Dark - alacritty color config
# Alexandre Gavioli (https://github.com/Alexx2/)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x101010'
foreground = '0xb9b9b9'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x101010'
cursor = '0xb9b9b9'

# Normal colors
[colors.normal]
black = '0x101010'
red = '0x7c7c7c'
green = '0x8e8e8e'
yellow = '0xa0a0a0'
blue = '0x686868'
magenta = '0x747474'
cyan = '0x868686'
white = '0xb9b9b9'

# Bright colors
[colors.bright]
black = '0x525252'
red = '0x999999'
green = '0x252525'
yellow = '0x464646'
blue = '0xababab'
magenta = '0xe3e3e3'
cyan = '0x5e5e5e'
white = '0xf7f7f7'
