require('lualine').setup({
  options = {
    icons_enabled = true,
    theme = 'onedark',
    component_separators = { left = '', right = '' },
    section_separators = { left = '', right = '' },
    disabled_filetypes = {
      statusline = { 'NvimTree' },
      winbar = { 'NvimTree' },
      NvimTree = {},
    },
    ignore_focus = {},
    always_divide_middle = true,
    globalstatus = true,
    refresh = {
      statusline = 1000,
      tabline = 1000,
      winbar = 1000,
    },
  },
  tabline = {},
  sections = {
    lualine_a = {},
    lualine_b = { 'branch', 'diff' },
    lualine_c = {},
    lualine_x = {},
    lualine_y = {},
    lualine_z = {},
  },
  winbar = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = { { 'filetype', icon_only = true }, '%F', '%m' },
    lualine_x = {},
    lualine_y = { 'encoding', 'location' },
    lualine_z = {},
  },
  inactive_winbar = {
    lualine_a = {},
    lualine_b = { { 'filetype', icon_only = true }, '%F', '%m' },
    lualine_c = {},
    lualine_x = {},
    lualine_y = {},
    lualine_z = {},
  },
})
