fork = false
frame = "none"
idle = true
maximized = false
# neovim-bin = "/opt/homebrew/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = false
theme = "auto"
title-hidden = true
vsync = true
wsl = false


