return {
  "stevearc/oil.nvim",
  enabled = true,
  cmd = "Oil",
  keys = {
    { "<leader>x", "<CMD>Oil<CR>" },
  },
  dependencies = {
    "nvim-tree/nvim-web-devicons",
  },
  opts = {
    delete_to_trash = true,
    use_default_keymaps = false,
    view_options = { show_hidden = true },
    constrain_cursor = "name",
    columns = {
      "icon",
      -- "permissions",
      -- "size",
      -- "mtime",
    },
    keymaps = {
      ["g?"] = "actions.show_help",
      ["<CR>"] = "actions.select",
      -- ["<C-s>"] = "actions.select_vsplit",
      -- ["<C-h>"] = "actions.select_split",
      -- ["<C-t>"] = "actions.select_tab",
      -- ["<C-p>"] = "actions.preview",
      -- ["<C-c>"] = "actions.close",
      -- ["<C-l>"] = "actions.refresh",
      ["-"] = "actions.parent",
      -- ["_"] = "actions.open_cwd",
      -- ["`"] = "actions.cd",
      -- ["~"] = "actions.tcd",
      -- ["gs"] = "actions.change_sort",
      -- ["gx"] = "actions.open_external",
      -- ["g."] = "actions.toggle_hidden",
      -- ["g\\"] = "actions.toggle_trash",
    },
  },
}
