return {
  "mrjones2014/smart-splits.nvim",
  keys = {
    -- resize
    {
      "<S-Down>",
      function()
        require("smart-splits").resize_down()
      end,
    },
    {
      "<S-Left>",
      function()
        require("smart-splits").resize_left()
      end,
    },
    {
      "<S-Right>",
      function()
        require("smart-splits").resize_right()
      end,
    },
    {
      "<S-Up>",
      function()
        require("smart-splits").resize_up()
      end,
    },
    -- moving
    {
      "<C-h>",
      function()
        require("smart-splits").move_cursor_left()
      end,
    },
    {
      "<C-j>",
      function()
        require("smart-splits").move_cursor_down()
      end,
    },
    {
      "<C-k>",
      function()
        require("smart-splits").move_cursor_up()
      end,
    },
    {
      "<C-l>",
      function()
        require("smart-splits").move_cursor_right()
      end,
    },
    -- swapping
    {
      "<leader><leader>h",
      function()
        require("smart-splits").swap_buf_left()
      end,
    },
    {
      "<leader><leader>j",
      function()
        require("smart-splits").swap_buf_down()
      end,
    },
    {
      "<leader><leader>k",
      function()
        require("smart-splits").swap_buf_up()
      end,
    },
    {
      "<leader><leader>l",
      function()
        require("smart-splits").swap_buf_right()
      end,
    },
  },
  opts = {},
}
